### ISSUE TITLE
404 not found on send_reply

### ISSUE THREAD

**Issue by saidganim** [vasilcovsky/errbot-backend-botframework#3]
Hi @vasilcovsky , Do you have any ideas why I get 404 Not found on post request in send_reply and send_feedback functions? Thank you in advance.

P.S. I am using your backend for the MS Teams app.

**Comment by igor-v-wqpredtech** [comment]
Hi @saidganim, I can take a look

**Comment by vasilcovsky** [comment]
Hi @saidganim, I can take a look

**Comment by saidganim** [comment]
@vasilcovsky  Thank you, I am also looking into API reference. Everything in your backend makes sense for me. Don't see any errors with URL :(

**Comment by vasilcovsky** [comment]
I just checked that backend works as expected and there are no changes in BotFramework API. Please check the following: 

1. Webserver plugin is activated in Errbot by running !status command 
2. Web server exposed to the world. 
3. You registered Bot in Azure Portal - specified endpoint (https://<your-host>/botframework) and obtained application id and passwd. 

You can debug integration locally by running Bot Framework Emulator and point it to http://localhost:3141/botframework  

Bot Framework Emulator:  https://docs.microsoft.com/en-us/azure/bot-service/bot-service-debug-emulator?view=azure-bot-service-4.0

**Comment by saidganim** [comment]
@vasilcovsky Yes, bot framework works as it's expected. My problem is that when I send reply from bot to Teams User(using generated URL from $serviceURL/conversations/{}/activities/{}  I am getting 404 error. So every request from ms teams reaches the bot itself( I can see by logs).

**Comment by saidganim** [comment]
@vasilcovsky  the problem is with urljoin, it is written not correctly, I will send a PR later.
