### ISSUE TITLE
Future plans with this backend

### ISSUE THREAD

**Issue by codablock** [vasilcovsky/errbot-backend-botframework#7]
Hello, I would have preferred to contact you directly @vasilcovsky but I couldn't find a way to do so. What are the future plans in supporting this backend? I've found multiple issues and missing functionality with it which I fixed locally. I see that this repo did not have much changes in the past, so I'd like to first figure out if it makes sense to create PR's against this repo or directly go with a fork?

**Comment by vasilcovsky** [comment]
Hi Alexander,

I don't have any plans for this backend but feel free to send PR.

Thanks, 
Igor

**Comment by codablock** [comment]
Please see https://github.com/vasilcovsky/errbot-backend-botframework/pull/8, which contains the mentioned changes
